# Generated by Django 2.2 on 2020-11-24 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('counter', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Counter')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Event')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Event type',
                'verbose_name_plural': 'Event types',
            },
        ),
        migrations.CreateModel(
            name='EventHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Detail')),
                ('creation_date', models.DateTimeField(blank=True, null=True, verbose_name='Creation Date')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemas.Event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Historia',
                'verbose_name_plural': 'Historia',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemas.EventType', verbose_name='Event'),
        ),
    ]
